### PR TITLE
Update Flaky.php

### PR DESCRIPTION
**Pull request by oldDriver**
I tried to use PHP Flaky from the box and i needed to do that changes in order it to works fine.
Does it make sense?
Thanks!

### CODE REVIEW

**Comment by jwarkentin** [comment]
Sorry I somehow missed the notification about your pull request and didn't see it until now. Thanks for contributing!

**Comment by ponchorage** [comment]
@jwarkentin You might consider removing the `Flaky` directory under `src`. That way you don't have the weird namespace of `Flaky\Flaky` and the even stranger use of the class as `\Flaky\Flaky\Flaky`. :)

**Comment by ponchorage** [comment]
Also looks like this requires the GMP PHP extension. Is there a way you can force that requirement in the composer.json?

**Comment by jwarkentin** [comment]
@ponchorage Both of those are done. I've removed the extra directory and added `ext-gmp` as a requirement in composer.json.

**Pull request merged**
